# Generated by Django 3.1.2 on 2023-03-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_no',
        ),
    ]
