# Generated by Django 3.1.2 on 2023-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_userprofile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
