# Generated by Django 3.1.2 on 2023-03-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
