# Generated by Django 3.1.2 on 2023-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_trend',
            field=models.BooleanField(default=False),
        ),
    ]
